FROM golang:1.7.0

RUN apt-get update && apt-get install -y less

RUN adduser --disabled-password --gecos '' fractals

WORKDIR /home/fractals/app
COPY . .
RUN chown -R fractals:fractals .

USER fractals
